# Generated by Django 4.2.7 on 2023-11-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_stockmarketdata_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockMarketData',
            new_name='StockMarketTaskData',
        ),
    ]
