# Generated by Django 4.2.7 on 2023-11-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_stockmarketdata_delete_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmarketdata',
            name='date',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
