# Generated by Django 4.2.7 on 2023-11-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rename_stockmarketdata_stockmarkettaskdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockMarketTaskData',
            new_name='SQLStockMarketTaskData',
        ),
    ]
